# Generated by Django 4.2.4 on 2025-02-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_billing',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name_billing',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name_billing',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='place_billing',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='zipcode_billing',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
