# Generated by Django 4.2.4 on 2023-12-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_kbank_charge_id_order_kbank_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('process', 'Processing'), ('shipped', 'Shipped'), ('paymentfail', 'Payment Fail')], default='ordered', max_length=20),
        ),
    ]
