# Generated by Django 4.2.4 on 2024-03-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kbank_token_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
