# Generated by Django 4.2.4 on 2025-02-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_amount',
            field=models.FloatField(blank=True, help_text='Total cost exclude shipping cost', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vat',
            field=models.FloatField(blank=True, help_text='VAT % of product amount', null=True),
        ),
    ]
