# Generated by Django 4.2.4 on 2025-03-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='order_id',
        ),
    ]
