# Generated by Django 4.2.4 on 2023-08-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_vendor_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
