# Generated by Django 4.2.4 on 2024-03-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_min_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor_price',
            new_name='vendor_class_A_price',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_class_B_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_class_C_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
