# Generated by Django 4.2.4 on 2025-02-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_category_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
