# Generated by Django 4.2.4 on 2025-03-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
