# Generated by Django 4.2.4 on 2023-12-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('process', 'Processing'), ('shipped', 'Shipped')], default='ordered', max_length=20),
        ),
    ]
