# Generated by Django 4.2.4 on 2025-02-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_address_billing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_amount',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
    ]
