# Generated by Django 4.2.4 on 2025-03-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_shippingrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
