# Generated by Django 4.2.4 on 2025-03-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_paid_amount_alter_order_product_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_url_printing',
            field=models.URLField(blank=True, null=True),
        ),
    ]
