# Generated by Django 4.2.4 on 2025-03-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_shipping_url_printing'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.CharField(default='PK38022-', max_length=255),
            preserve_default=False,
        ),
    ]
