# Generated by Django 4.2.4 on 2023-08-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
