# Generated by Django 4.2.4 on 2025-03-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_feature_product_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='feature',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='publish',
            new_name='is_published',
        ),
    ]
