# Generated by Django 4.2.4 on 2024-03-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_vendor_price_product_vendor_class_a_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_class_A_min_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_class_B_min_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_class_C_min_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
