# Generated by Django 4.2.4 on 2024-12-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_min_quantity_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=12, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
