# Generated by Django 4.2.4 on 2025-02-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_category_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='background',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='uploads/'),
        ),
    ]
